# Install or update Free-WAN on Windows. Run from PowerShell:
#
#   irm https://raw.githubusercontent.com/dmoore-dwmmholdings/free-wan/main/scripts/install.ps1 | iex
#
# Downloads the latest source from GitHub, builds it with Docker Desktop, and starts it behind a
# Tailscale sidecar. Containers use `restart: unless-stopped` and Docker Desktop is set to start
# at login, so the server comes back after a reboot. Re-run the same command to update: .env,
# data\ and docker-compose.override.yml are kept.
#
# Env:
#   FW_DIR  install directory          (default %USERPROFILE%\free-wan)
#   FW_REF  branch or tag to install   (default main)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue' # Invoke-WebRequest is very slow with the progress bar

$repo = 'dmoore-dwmmholdings/free-wan'
$ref = if ($env:FW_REF) { $env:FW_REF } else { 'main' }
$dir = if ($env:FW_DIR) { $env:FW_DIR } else { Join-Path $env:USERPROFILE 'free-wan' }

function Fail($msg) { Write-Host $msg -ForegroundColor Red; throw $msg }

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Fail 'Docker Desktop is required: https://docs.docker.com/desktop/setup/install/windows-install/'
}
cmd /c 'docker info >nul 2>&1'
if ($LASTEXITCODE -ne 0) { Fail 'Docker is installed but not running. Start Docker Desktop and re-run.' }

Write-Host "==> Downloading $repo@$ref"
$tmp = Join-Path ([IO.Path]::GetTempPath()) "free-wan-$([guid]::NewGuid())"
New-Item -ItemType Directory $tmp | Out-Null
try {
  $zip = Join-Path $tmp 'src.zip'
  Invoke-WebRequest -UseBasicParsing -OutFile $zip "https://codeload.github.com/$repo/zip/$ref"
  Expand-Archive $zip $tmp
  $src = Get-ChildItem $tmp -Directory | Select-Object -First 1

  # Mirror the source in, leaving local state alone (robocopy never purges excluded items).
  Write-Host "==> Installing into $dir"
  New-Item -ItemType Directory -Force $dir | Out-Null
  robocopy $src.FullName $dir /MIR /NFL /NDL /NJH /NJS /NP /XD data /XF .env docker-compose.override.yml | Out-Null
  if ($LASTEXITCODE -ge 8) { Fail "Copying files failed (robocopy exit $LASTEXITCODE)" }
} finally {
  Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}

Push-Location $dir
try {
  New-Item -ItemType Directory -Force data\tailscale | Out-Null

  if (Test-Path .env) {
    Write-Host '==> Keeping the existing .env'
  } else {
    Write-Host ''
    Write-Host 'Free-WAN is reachable only over your tailnet. Create a reusable, non-ephemeral'
    Write-Host 'auth key at https://login.tailscale.com/admin/settings/keys'
    $authkey = Read-Host 'Tailscale auth key (tskey-auth-...)'
    if (-not $authkey) { Fail 'An auth key is required.' }

    function New-Secret($n) {
      $b = New-Object byte[] $n
      [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
      [Convert]::ToBase64String($b) -replace '[+/=]', 'x'
    }
    $secret = New-Secret 48
    $adminpw = New-Secret 12

    # No BOM: docker compose would read it as part of the first variable name.
    [IO.File]::WriteAllText((Join-Path $dir '.env'), @"
# Generated by scripts/install.ps1
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$adminpw
SESSION_SECRET=$secret
TS_AUTHKEY=$authkey
COMMAND_ALLOWED_EXECUTABLES=
"@)
    Write-Host "==> Wrote .env. First-login admin password: $adminpw" -ForegroundColor Yellow
  }

  if (-not (Test-Path docker-compose.override.yml)) {
    [IO.File]::WriteAllText((Join-Path $dir 'docker-compose.override.yml'), @'
# Local additions, kept across updates. Mount media drives read-only, then add them in
# Admin -> Repositories using the container path (e.g. /media/movies), e.g.:
#
# services:
#   free-wan:
#     volumes:
#       - D:/Movies:/media/movies:ro
services: {}
'@)
  }

  Write-Host '==> Building and starting (the first build takes a few minutes)'
  # Compose writes progress to stderr; under 'Stop' PowerShell 5.1 can treat that as a failure.
  $ErrorActionPreference = 'Continue'
  docker compose up -d --build
  $ErrorActionPreference = 'Stop'
  if ($LASTEXITCODE -ne 0) { Fail 'docker compose up failed.' }
} finally {
  Pop-Location
}

# Containers only come back after a reboot if Docker Desktop itself starts at login.
$settings = Join-Path $env:APPDATA 'Docker\settings-store.json'
if (Test-Path $settings) {
  # Plain text edit: a ConvertTo-Json round trip in PowerShell 5.1 can mangle other settings.
  $text = [IO.File]::ReadAllText($settings)
  if ($text -match '"AutoStart"\s*:\s*false') {
    [IO.File]::WriteAllText($settings, ($text -replace '"AutoStart"\s*:\s*false', '"AutoStart": true'))
    Write-Host '==> Enabled "Start Docker Desktop when you sign in"'
  }
} else {
  Write-Host 'Turn on Docker Desktop -> Settings -> General -> "Start Docker Desktop when you sign in".' -ForegroundColor Yellow
}

Write-Host @"

==> Up. Free-WAN is at https://free-wan.<your-tailnet>.ts.net once Tailscale registers it.
    Sign in as "admin"; you are asked to change the password on first login.

    Media drives: edit $dir\docker-compose.override.yml, then re-run this installer.
    Update later: re-run the same irm ... | iex command.
"@
