#!/usr/bin/env bash
# Install or update Free-WAN with Docker. Works in Git Bash on Windows, Linux and macOS:
#
#   curl -fsSL https://raw.githubusercontent.com/dmoore-dwmmholdings/free-wan/main/scripts/install.sh | bash
#
# Downloads the latest source from GitHub, builds it, and starts it on your tailnet: behind a
# Tailscale sidecar container, or with FW_TAILSCALE=host through the Tailscale already installed
# on this machine. Use host on Windows: Docker Desktop's networking pushes the sidecar through a
# slow relay, where Tailscale on Windows connects devices directly. Containers use
# `restart: unless-stopped`, and on Windows Docker Desktop is set to start at sign-in, so the
# server comes back after a reboot. Re-run the same command to update: .env (including the
# Tailscale choice), data/ and docker-compose.override.yml are kept.
#
# Env:
#   FW_DIR         install directory          (default ~/free-wan)
#   FW_REF         branch or tag to install   (default main)
#   FW_TAILSCALE   container or host          (default: the last choice, else container)
#   FW_TS_AUTHKEY  Tailscale auth key for the container; skips the prompt

set -euo pipefail

REPO="${FW_REPO:-dmoore-dwmmholdings/free-wan}"
REF="${FW_REF:-main}"
dir="${FW_DIR:-$HOME/free-wan}"
marker=".free-wan-install"

fail() { echo "$1" >&2; exit 1; }

command -v curl >/dev/null || fail "curl is required"
command -v tar >/dev/null || fail "tar is required"
command -v docker >/dev/null || fail "Docker is required: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
docker info >/dev/null 2>&1 || fail "Docker is installed but not running. Start it and re-run."

# Refuse to replace the contents of a folder this script did not create.
if [ -d "$dir" ] && [ -n "$(ls -A "$dir")" ] && [ ! -f "$dir/$marker" ] && [ ! -f "$dir/Dockerfile" ]; then
  fail "$dir exists and is not a Free-WAN install. Set FW_DIR to another folder."
fi

echo "==> Downloading $REPO@$REF"
work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT
curl -fsSL "https://codeload.github.com/$REPO/tar.gz/$REF" | tar -xz -C "$work"
src="$(find "$work" -mindepth 1 -maxdepth 1 -type d | head -1)"

# Replace the code, keeping local state, so files deleted upstream do not linger.
echo "==> Installing into $dir"
mkdir -p "$dir"
find "$dir" -mindepth 1 -maxdepth 1 \
  ! -name data ! -name .env ! -name docker-compose.override.yml ! -name "$marker" \
  -exec rm -rf {} +
cp -R "$src/." "$dir/"
touch "$dir/$marker"
cd "$dir"
mkdir -p data/tailscale

secret() { head -c "$1" /dev/urandom | base64 | tr -d '\n+/='; }
envget() { grep "^$1=" .env 2>/dev/null | cut -d= -f2- || true; }
# Sets or removes (no value) one line of .env, keeping it private.
envset() {
  (umask 077; { grep -v "^$1=" .env || true; [ $# -lt 2 ] || printf '%s=%s\n' "$1" "$2"; } > .env.tmp)
  mv .env.tmp .env
}

mode="${FW_TAILSCALE:-$(envget TAILSCALE_MODE)}"
mode="${mode:-container}"
case "$mode" in
  container|host) ;;
  *) fail "FW_TAILSCALE must be container or host" ;;
esac
if [ "$mode" = host ]; then
  command -v tailscale >/dev/null || fail "FW_TAILSCALE=host needs Tailscale on this machine: https://tailscale.com/download"
  tailscale status >/dev/null 2>&1 || fail "Tailscale is installed but not signed in. Sign in, then re-run."
fi

authkey() {
  local key="${FW_TS_AUTHKEY:-}"
  if [ -z "$key" ]; then
    # Piped into bash, stdin is this script, so the prompt reads from the terminal.
    [ -r /dev/tty ] || fail "No terminal for the prompt. Set FW_TS_AUTHKEY and re-run."
    echo >&2
    echo "Free-WAN is reachable only over your tailnet. Create a reusable, non-ephemeral" >&2
    echo "auth key at https://login.tailscale.com/admin/settings/keys" >&2
    read -r -p "Tailscale auth key (tskey-auth-...): " key < /dev/tty
  fi
  [ -n "$key" ] || fail "An auth key is required."
  printf '%s' "$key"
}

if [ -f .env ]; then
  echo "==> Keeping the existing .env"
else
  key=""
  [ "$mode" = host ] || key="$(authkey)"
  adminpw="$(secret 12)"
  umask 077
  cat > .env <<ENV
# Generated by scripts/install.sh
ADMIN_USERNAME=admin
ADMIN_PASSWORD=$adminpw
SESSION_SECRET=$(secret 48)
TS_AUTHKEY=$key
COMMAND_ALLOWED_EXECUTABLES=
ENV
  umask 022
  echo "==> Wrote .env (secrets generated)"
fi

# Remember the Tailscale choice; Compose reads COMPOSE_FILE from .env, so plain `docker compose`
# commands use it too.
envset TAILSCALE_MODE "$mode"
if [ "$mode" = host ]; then
  envset COMPOSE_PATH_SEPARATOR ":"
  envset COMPOSE_FILE "docker-compose.yml:docker-compose.host-tailscale.yml:docker-compose.override.yml"
else
  envset COMPOSE_PATH_SEPARATOR
  envset COMPOSE_FILE
  [ -n "$(envget TS_AUTHKEY)" ] || envset TS_AUTHKEY "$(authkey)"
fi

if [ ! -f docker-compose.override.yml ]; then
  cat > docker-compose.override.yml <<'YML'
# Local additions, kept across updates. Mount media drives read-only, then add them in
# Admin -> Repositories using the container path (e.g. /media/movies), e.g.:
#
# services:
#   free-wan:
#     volumes:
#       - D:/Movies:/media/movies:ro      # Windows
#       - /mnt/movies:/media/movies:ro    # Linux
services: {}
YML
fi

echo "==> Building and starting (the first build takes a few minutes)"
# Moving to host Tailscale: the sidecar container is no longer part of the project.
[ "$mode" = container ] || docker rm -f free-wan-ts >/dev/null 2>&1 || true
docker compose up -d --build

# Containers only come back after a reboot if Docker itself starts on its own.
settings="${APPDATA:-}/Docker/settings-store.json"
if [ -n "${APPDATA:-}" ] && [ -f "$settings" ]; then
  if grep -Eq '"AutoStart" *: *false' "$settings"; then
    sed -i -E 's/"AutoStart" *: *false/"AutoStart": true/' "$settings"
    echo "==> Enabled \"Start Docker Desktop when you sign in\""
  fi
elif command -v systemctl >/dev/null && ! systemctl is-enabled docker >/dev/null 2>&1; then
  echo "Docker does not start at boot. Run: sudo systemctl enable docker"
fi

url=""
if [ "$mode" = host ]; then
  echo "==> Publishing on your tailnet with this machine's Tailscale"
  # HTTPS on the machine's own tailnet name, kept across reboots. --yes skips prompts.
  tailscale serve --bg --yes 8080 </dev/null >/dev/null 2>&1 || tailscale serve --bg 8080 </dev/null \
    || echo "tailscale serve failed: turn on HTTPS certificates in the Tailscale admin console (DNS), then re-run."
  # Windows: stay connected with nobody signed in, as a server should.
  [ -z "${APPDATA:-}" ] || tailscale set --unattended=true >/dev/null 2>&1 || true
  dns="$(tailscale status --json --peers=false 2>/dev/null | grep -o '"DNSName": *"[^"]*"' | head -1 | cut -d'"' -f4 || true)"
  [ -z "$dns" ] || url="https://${dns%.}"
else
  # The node can take a few seconds to register; its name gets a suffix (free-wan-1) when
  # another machine on the tailnet already uses free-wan.
  echo "==> Waiting for Tailscale to register the server"
  for _ in $(seq 1 30); do
    dns="$(docker exec free-wan-ts tailscale status --json --peers=false 2>/dev/null     | grep -o '"DNSName": *"[^"]*"' | head -1 | cut -d'"' -f4 || true)"
    if [ -n "$dns" ]; then url="https://${dns%.}"; break; fi
    sleep 2
  done
fi

if [ "$mode" = host ]; then
  missing="https://<this-machine>.<your-tailnet>.ts.net (run: tailscale serve status)"
else
  missing="https://free-wan.<your-tailnet>.ts.net (not registered yet; run: docker logs free-wan-ts)"
fi
user="$(grep '^ADMIN_USERNAME=' .env | cut -d= -f2- || true)"
pass="$(grep '^ADMIN_PASSWORD=' .env | cut -d= -f2- || true)"

cat <<DONE

==> Free-WAN is running.

    Open:      ${url:-$missing}
    Username:  ${user:-admin}
    Password:  ${pass:-printed in: docker logs free-wan}

    You are asked to choose a new password on first sign-in. Until then, the password
    above is also in $dir/.env.

    Media drives: edit $dir/docker-compose.override.yml, then re-run this installer.
    Update later: re-run the same curl ... | bash command.
DONE
